# Generated by Django 2.1.12 on 2020-01-08 03:53

import Quizs.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VefriAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.DecimalField(decimal_places=0, max_digits=13, null=True, validators=[Quizs.validator.validate_phone])),
                ('gender', models.CharField(max_length=255, null=True)),
                ('old', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=50)),
                ('token', models.TextField(max_length=200)),
            ],
        ),
    ]
