# Generated by Django 2.1.12 on 2020-01-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizs', '0002_vefriaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vefriaccount',
            name='password',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vefriaccount',
            name='token',
            field=models.TextField(max_length=255),
        ),
    ]
