# Generated by Django 2.1.12 on 2020-01-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizs', '0003_auto_20200108_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vefriaccount',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
    ]
