# Generated by Django 2.1.12 on 2020-01-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizs', '0004_auto_20200108_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(max_length=255)),
            ],
        ),
    ]
