# Generated by Django 2.1.12 on 2020-01-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizs', '0005_resetpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Nũ'), (1, 'Nam'), (2, 'Không xác định')], default=0, null=True),
        ),
    ]
