# Generated by Django 2.1.12 on 2020-01-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizs', '0006_auto_20200109_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
